<?php
/**
 * Implements hook_block_info().
 */
function deviations_selector_block_info() {
  $blocks['selector1'] = array('info' => t('Deviation Selector 1'),);
  $blocks['selector2'] = array('info' => t('Deviation Selector 2'),);
  $blocks['selector3'] = array('info' => t('Deviation Selector 3'),);
  $blocks['selector4'] = array('info' => t('Deviation Selector 4'),);
  $blocks['selector_info'] = array('info' => t('Deviation Selector Info'),);
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function deviations_selector_block_view($delta='') {
  $block = array();
  switch($delta) {
    case 'selector1' :
      $terms = taxonomy_get_tree(1,0,1);
      $block['content'] .= '<div id="selector1">';
      $block['content'].='<ul class="selector1">';
      foreach ($terms as $i => $term){
        $block['content'] .= _deviations_selector_display_term(
          $term->tid, 
          $term->name, 
          $i, 
          0);
      }
      $block['content'].='</ul>';
      $block['content'].='</div>';
      break;
    case 'selector2' :
      $terms = taxonomy_get_tree(1,arg(1),1);
      $block['content'] .= '<div id="selector2">';
      $block['content'].='<ul class="selector2">';
      foreach ($terms as $i => $term){
        $block['content'] .= _deviations_selector_display_term(
          $term->tid, 
          $term->name, 
          $i, 
          1);
      }
      $block['content'].='</ul>';
      $block['content'].='</div>';
      break;
    case 'selector3' :
      $terms = taxonomy_get_tree(1,arg(2),1);
      $block['content'] .= '<div id="selector3">';
      $block['content'].='<ul class="selector3">';
      foreach ($terms as $i => $term){
        $block['content'] .= _deviations_selector_display_term(
          $term->tid, 
          $term->name, 
          $i, 
          2);
      }
      $block['content'].='</ul>';
      $block['content'].='</div>';
      break;
    case 'selector4' :
      $terms = taxonomy_get_tree(1,arg(3),1);
      $block['content'] .= '<div id="selector4">';
      $block['content'].='<ul class="selector4">';
      foreach ($terms as $i => $term){
        $block['content'] .= _deviations_selector_display_term(
          $term->tid, 
          $term->name, 
          $i, 
          3);
      }
      $block['content'].='</ul>';
      $block['content'].='</div>';
      break;
    case 'selector_info' :
      $arguments = arg();
      $last_arg = array_pop($arguments);
      $term = taxonomy_term_load($last_arg);
      $count = count(taxonomy_get_children($last_arg));
      if ($count>0) {
        $block['content'] .= '<div id="selector_info">';
        $block['content'] .= 'Please select a location to report a deviation. You also need to make sure location at the lowest possible detail level.';
        $block['content'] .= '</div>';
      } else {
        $block ['content'] .= '<a href="/node/add/article?edit[field_tags][und]='.$term->tid.'">Add decation to '.$term->name.'</a>';
      }
      break;
  } #[field][tags][und]-0-tid
  return $block;
}

function _deviations_selector_display_term($tid, $name, $i, $level) {
  $class = _deviations_selector_alternatingstyle($i);
  $count = count(taxonomy_get_children($tid));
  if (arg($level+1)==$tid) $class .= " selected ";
  $ret.='<li class="' . $class . '">';
  if ($count>0) {
    $ret.=_deviations_selector_make_link($level,$tid);
    $ret.=$name;
    $ret.=' ('.$count.')';
    $ret.='</a>';
  } else {
    $ret.=_deviations_selector_make_link($level,$tid);
    $ret.=$name;
    $ret.='</a>';
  }
  return $ret;
}

function _deviations_selector_make_link ($level,$tid) {
  $link.=arg(0).'/';
  for($i=0; $i<$level; $i++) $link.=arg($i+1).'/';
  $ret.='<a href="/'.$link.$tid.'/">';
  return $ret;
}

function _deviations_selector_alternatingstyle($i){
  if ( $i & 1 ) {
    return 'odd';
  } else {
    return 'even';
  }
}
