<?php
/**
 * Implements hook_block_info().
 */
function deviations_selector_block_info() {
  $blocks['selector1'] = array('info' => t('Deviation Selector 1'),);
  $blocks['selector2'] = array('info' => t('Deviation Selector 2'),);
  $blocks['selector3'] = array('info' => t('Deviation Selector 3'),);
  $blocks['selector4'] = array('info' => t('Deviation Selector 4'),);
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function deviations_selector_block_view($delta='') {
  $block = array();
  
  switch($delta) {
    case 'selector1' :
      $terms = taxonomy_get_tree(1,0,1);
      $block['content'].='<ul class="selector1">';
      foreach ($terms as $i => $term){
        $block['content'] .= _deviations_selector_display_term(
          $term->tid, 
          $term->name, 
          $i, 
          0);
      }
      $block['content'].='</ul>';
      break;
    case 'selector2' :
      $terms = taxonomy_get_tree(1,arg(1),1);
      $block['content'].='<ul class="selector2">';
      foreach ($terms as $i => $term){
        $block['content'] .= _deviations_selector_display_term(
          $term->tid, 
          $term->name, 
          $i, 
          1);
      }
      $block['content'].='</ul>';
      break;
    case 'selector3' :
      $terms = taxonomy_get_tree(1,arg(2),1);
      $block['content'].='<ul class="selector3">';
      foreach ($terms as $i => $term){
        $block['content'] .= _deviations_selector_display_term(
          $term->tid, 
          $term->name, 
          $i, 
          1);
      }
      $block['content'].='</ul>';
      break;
    case 'selector4' :
      $terms = taxonomy_get_tree(1,arg(3),1);
      $block['content'].='<ul class="selector4">';
      foreach ($terms as $i => $term){
        $block['content'] .= _deviations_selector_display_term(
          $term->tid, 
          $term->name, 
          $i, 
          1);
      }
      $block['content'].='</ul>';
      break;
  }
  return $block;
}

function _deviations_selector_display_term($tid, $name, $i, $level) {
  $class = _deviations_selector_alternatingstyle($i);
  $count = count(taxonomy_get_children($tid));
  if (arg($level+1)==$tid) $class .= " selected ";
  $ret.='<li class="' . $class . '">';
  if ($count>0) {
    $ret.=_deviations_selector_make_link($level,$tid);
    $ret.=$name;
    $ret.=' ('.$count.')';
    $ret.='</a>';
  } else {
    $ret.=_deviations_selector_make_link($level,$tid);
    $ret.=$name;
    $ret.='</a>';
  }
  return $ret;
}

function _deviations_selector_make_link ($level,$tid) {
  drupal
  $link.=arg(0).'/';
  for($i=0; $i<$level; $i++) {
    $link.=arg($i+1).'/';
    drupal_set_message($i);
  }
  $ret.='<a href="/'.$link.$tid.'/">';
  for($i = 400; $i > 0; $i--)
  {
    $ret.=$1;
  }
  return $ret;
}

function _deviations_selector_alternatingstyle($i){
  if ( $i & 1 ) {
    return 'odd';
  } else {
    return 'even';
  }
}
